package csu.view.oper;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;

import csu.app.MainUI;
import csu.tiles.MainTiles;
import csu.view.oper.AppFormsView;

@SuppressWarnings("serial")
public class OperMenu extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private AbsoluteLayout mainLayout;
	private MenuBar menuBar;
	private MainTiles mainUI;
	private MainUI app;
	
	public OperMenu(MainTiles mainUI, MainUI app) {
		this.app = app;
		this.mainUI = mainUI;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// menuBar
		menuBar = new MenuBar();
		menuBar.setImmediate(false);
		menuBar.setWidth("100.0%");
		menuBar.setHeight("-1px");
		MenuBar.MenuItem docsMenu = menuBar.addItem("Документы", null, null);
		MenuBar.MenuItem dictsMenu = menuBar.addItem("Отчеты", null, null);
		MenuBar.Command mycommand = new MenuBar.Command() {
			@Override
			public void menuSelected(MenuItem selectedItem) {
		        mainUI.getBodyLayout().removeAllComponents();
		        if (selectedItem.getText() == "Заявление") {
		        	mainUI.getBodyLayout().addComponent(new AppFormsView(app));
		        	
				}
		        
			}
		};

		docsMenu.addItem("-", null, null);
		docsMenu.addItem("Заявление", null, mycommand);
		docsMenu.addItem("-", null, null);
		dictsMenu.addItem("-", null, null);
		dictsMenu.addItem("Отчет", null, mycommand);
		dictsMenu.addItem("-", null, null);
		mainLayout.addComponent(menuBar, "top:0.0px;left:0.0px;");
		menuBar.setImmediate(true);
		return mainLayout;
	}

}
