package csu.tiles;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.MouseEvents.ClickEvent;
import com.vaadin.event.MouseEvents.ClickListener;
import com.vaadin.navigator.Navigator;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

public class HeaderUI extends CustomComponent {
	private static final long serialVersionUID = -1931057876407837924L;
	private AbsoluteLayout mainLayout = new AbsoluteLayout();
	private Panel headerPanel = new Panel();
	private VerticalLayout verticalLayout_1;
	private HorizontalLayout horizontalLayout_1;
	private HorizontalLayout verticalLayout_4;
	private Label label_user;
	private VerticalLayout verticalLayout_3;
	private Label label_name;
	private VerticalLayout verticalLayout_2;
	private Label label_logo;
	private Navigator navigator;

	public HeaderUI(Navigator navigator) {
		this.navigator = navigator;
		this.setSizeFull();

		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		
		// panel_1
		headerPanel.setImmediate(false);
		headerPanel.setSizeFull();
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		headerPanel.setContent(verticalLayout_1);

		mainLayout.addComponent(headerPanel, "top:0.0px;left:0.0px;");
		
		setCompositionRoot(mainLayout);
		
	}

	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("98.0%");
		verticalLayout_1.setHeight("98.0%");
		verticalLayout_1.setMargin(false);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_1.addComponent(horizontalLayout_1);
		verticalLayout_1.setComponentAlignment(horizontalLayout_1,new Alignment(48));
		
		return verticalLayout_1;
	}

	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_1.addComponent(verticalLayout_2);
		horizontalLayout_1.setExpandRatio(verticalLayout_2, 1.0f);
		horizontalLayout_1.setComponentAlignment(verticalLayout_2,
				new Alignment(48));
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		horizontalLayout_1.addComponent(verticalLayout_3);
		horizontalLayout_1.setExpandRatio(verticalLayout_3, 1.0f);
		horizontalLayout_1.setComponentAlignment(verticalLayout_3,
				new Alignment(48));
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		horizontalLayout_1.addComponent(verticalLayout_4);
		horizontalLayout_1.setExpandRatio(verticalLayout_4, 1.0f);
		horizontalLayout_1.setComponentAlignment(verticalLayout_4, Alignment.MIDDLE_RIGHT);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		
		// label_logo
		label_logo = new Label();
		label_logo.setImmediate(false);
		label_logo.setWidth("-1px");
		label_logo.setHeight("-1px");
		label_logo.setValue("LOGO");
		verticalLayout_2.addComponent(label_logo);
		verticalLayout_2.setComponentAlignment(label_logo, new Alignment(48));
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(false);
		
		// label_name
		label_name = new Label();
		label_name.setImmediate(false);
		label_name.setWidth("-1px");
		label_name.setHeight("-1px");
		label_name.setValue("APPLICATION NAME");
		verticalLayout_3.addComponent(label_name);
		verticalLayout_3.setComponentAlignment(label_name, new Alignment(48));
		
		return verticalLayout_3;
	}

	private HorizontalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new HorizontalLayout();
		verticalLayout_4.setImmediate(true);
		verticalLayout_4.setWidth("100.0%");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(false);
		
//		 label_user
		label_user = new Label();
		label_user.setImmediate(false);
		label_user.setWidth("-1px");
		label_user.setHeight("-1px");
		
		try {
			label_user.setValue(UI.getCurrent().getSession().getAttribute("user_first_name").toString()+" "+UI.getCurrent().getSession().getAttribute("user_surname").toString());
			
		} catch (Exception e) {
			System.out.println(e);
		}
		verticalLayout_4.addComponent(label_user);
		verticalLayout_4.setComponentAlignment(label_user, Alignment.MIDDLE_RIGHT);
		
		Image logout = new Image();
		logout.setSource(new ThemeResource("img/application_exit8x8.png"));
		logout.setDescription("Выйти");
		logout.setWidth("16px");
		logout.setHeight("16px");
		
		verticalLayout_4.addComponent(logout);
		verticalLayout_4.setSizeUndefined();
		verticalLayout_4.setSpacing(true);
		verticalLayout_4.setComponentAlignment(logout, Alignment.MIDDLE_RIGHT);
		logout.addClickListener(new ClickListener() {
			private static final long serialVersionUID = 7963017916648543231L;
			@Override
			public void click(ClickEvent event) {
				UI.getCurrent().getSession().setAttribute("user_id", null);
				navigator.navigateTo("");
			}
		});
		
		return verticalLayout_4;
	}
}
